"""Unified database access for the agent tier.

When DATABASE_URL is set (postgresql://...), every agent talks to PostgreSQL —
one network endpoint shared by all tiers, no file paths, no HTTP/Redis
fallback hacks. When it is unset, behavior is unchanged: SQLite at the path
each caller already uses.

The wrapper exposes the small DB-API subset the agents use (execute/cursor/
executemany/commit/rollback/close, fetchone/fetchall) and translates the
SQLite '?' placeholder style to psycopg's '%s'. Postgres NUMERIC aggregates
(AVG/SUM) are converted from Decimal to float so downstream math and
json.dumps keep working identically to SQLite.

Dialect notes for SQL written by agents:
- Use ON CONFLICT upserts (both dialects) instead of INSERT OR REPLACE/IGNORE.
- Use AUTO_PK below instead of INTEGER PRIMARY KEY AUTOINCREMENT.
- Use LOWER(col) = LOWER(?) instead of COLLATE NOCASE.
- Store dates as ISO TEXT, not DATE, so both dialects return strings.
"""
import os
import sqlite3
from contextlib import contextmanager
from decimal import Decimal

DATABASE_URL = os.getenv("DATABASE_URL", "")
IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))

# Auto-incrementing integer primary key, per dialect.
AUTO_PK = (
    "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    if IS_POSTGRES
    else "INTEGER PRIMARY KEY AUTOINCREMENT"
)

DEFAULT_TIMEOUT = 5.0


def db_available(db_path: str) -> bool:
    """True when there is a database to talk to.

    Postgres: always (connection errors surface loudly on connect, which is
    the behavior we want — a wrong DSN must never silently no-op the way a
    wrong file path does). SQLite: only when the file already exists, so
    read-side callers don't create empty stray databases.
    """
    return IS_POSTGRES or os.path.exists(db_path)


def _pg_sql(sql: str) -> str:
    # Agent SQL never contains a literal '?' outside a placeholder position.
    return sql.replace("?", "%s")


def _from_pg(value):
    return float(value) if isinstance(value, Decimal) else value


class _PgCursor:
    """psycopg cursor adapter: '?' placeholders + Decimal→float rows."""

    def __init__(self, cur):
        self._cur = cur

    def execute(self, sql: str, params=()):
        self._cur.execute(_pg_sql(sql), params)
        return self

    def executemany(self, sql: str, seq_of_params):
        self._cur.executemany(_pg_sql(sql), seq_of_params)
        return self

    def fetchone(self):
        row = self._cur.fetchone()
        return None if row is None else tuple(_from_pg(v) for v in row)

    def fetchall(self):
        return [tuple(_from_pg(v) for v in row) for row in self._cur.fetchall()]

    def fetchmany(self, size=None):
        rows = self._cur.fetchmany(size) if size is not None else self._cur.fetchmany()
        return [tuple(_from_pg(v) for v in row) for row in rows]

    def close(self):
        self._cur.close()

    @property
    def rowcount(self):
        return self._cur.rowcount

    def __iter__(self):
        for row in self._cur:
            yield tuple(_from_pg(v) for v in row)


class _PgConnection:
    """psycopg connection adapter matching the sqlite3.Connection surface."""

    def __init__(self, conn):
        self._conn = conn

    def execute(self, sql: str, params=()):
        return _PgCursor(self._conn.cursor()).execute(sql, params)

    def executemany(self, sql: str, seq_of_params):
        return _PgCursor(self._conn.cursor()).executemany(sql, seq_of_params)

    def cursor(self):
        return _PgCursor(self._conn.cursor())

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


def connect(db_path: str, timeout: float = DEFAULT_TIMEOUT):
    """Open a connection: Postgres when DATABASE_URL is set, else SQLite."""
    if IS_POSTGRES:
        import psycopg

        return _PgConnection(
            psycopg.connect(DATABASE_URL, connect_timeout=max(int(timeout), 1))
        )
    return sqlite3.connect(db_path, timeout=timeout)


@contextmanager
def transaction(db_path: str, timeout: float = DEFAULT_TIMEOUT):
    """One connection whose work commits on success, rolls back on error."""
    conn = connect(db_path, timeout=timeout)
    try:
        yield conn
        conn.commit()
    except BaseException:
        conn.rollback()
        raise
    finally:
        conn.close()
