"""Minutes, and the rate that comes with them -- sampled together, because they arrive together.

Two defects in the original simulator lived here.

**Minutes were unimodal.** A truncated Gaussian is a fine description of a locked-in starter and
a poor one for anybody whose role is in question, because that player's minutes are not
uncertain around 22 -- they are 30 if they start and 11 if they do not. Averaging the two
produces a number that describes no game the player has ever played, and it understates both
tails at once. :class:`MinutesModel` keeps the two regimes separate and mixes them with the
start probability the role model already computed and the pipeline was already discarding.

**Minutes and rate were sampled independently.** The old loop drew minutes from a Gaussian and,
separately, drew a per-minute rate uniformly from the last twenty games. Two things went wrong.
The pairing was destroyed -- a night's usage rate belongs to that night's minutes -- and short
outings entered the pool at face value, so four minutes and two points became 0.5 points per
minute, which at a 32-minute projection is a sixteen-point draw generated by four minutes of
evidence. :class:`JointSampler` shrinks each game's rate by how many minutes support it and
resamples the ``(minutes deviation, rate)`` pair together.
"""

from __future__ import annotations

import math
import random
from collections.abc import Sequence
from dataclasses import dataclass

from wnba_services.forecasting.recency import half_life_weights, weighted_mean

__all__ = [
    "MAX_MINUTES",
    "GameObservation",
    "JointSampler",
    "MinutesModel",
    "RestAdjustment",
    "build_joint_sampler",
    "build_minutes_model",
    "rest_adjustment",
]

MAX_MINUTES = 45.0

# Minutes of evidence a game must carry before its per-minute rate is believed at face value.
# Roughly a third of a starter's night: enough that garbage time cannot dominate, small enough
# that a real rotation player's ordinary game is barely shrunk at all.
_RATE_PRIOR_MINUTES = 12.0
_MIN_REGIME_GAMES = 4
_MIN_MINUTES_STD = 1.5
_MAX_MINUTES_STD = 14.0


@dataclass(frozen=True)
class GameObservation:
    """One historical game reduced to what the sampler needs."""

    minutes: float
    stat: float


@dataclass(frozen=True)
class RestAdjustment:
    """Bounded multipliers for schedule density.

    Signed priors, not fitted coefficients, and deliberately small. The back-to-back effect on
    minutes is well established in principle and modest in size; publishing a large adjustment
    from an unfitted prior would be inventing precision. These become learned parameters once
    enough settled episodes carry rest as a feature -- which they now do, because the forecast
    finally records it.
    """

    minutes_multiplier: float
    rate_multiplier: float


def rest_adjustment(
    team_rest_days: float | None, opponent_rest_days: float | None
) -> RestAdjustment:
    """Minutes and efficiency multipliers implied by days of rest on both sides.

    The pipeline computed ``team_rest_days`` and ``opponent_rest_days`` in the matchup feature,
    wrote them into the feature snapshot, and then never read them again. This is where they
    finally do something.
    """
    if team_rest_days is None:
        return RestAdjustment(1.0, 1.0)

    if team_rest_days < 1.5:
        # Second night of a back-to-back: rotations shorten and legs are worse.
        minutes, rate = 0.97, 0.985
    elif team_rest_days < 2.5:
        minutes, rate = 1.0, 1.0
    else:
        # Extended rest restores minutes but brings a little rust with it.
        minutes, rate = 1.01, 0.995

    if opponent_rest_days is not None and opponent_rest_days < 1.5 and team_rest_days >= 2.5:
        # A tired opponent concedes efficiency; it does not lengthen our rotation.
        rate *= 1.01
    return RestAdjustment(minutes, rate)


@dataclass(frozen=True)
class MinutesModel:
    """A two-regime minutes distribution: starter, bench, mixed by start probability."""

    starter_mean: float
    starter_std: float
    bench_mean: float
    bench_std: float
    start_probability: float

    @property
    def expected_minutes(self) -> float:
        return (
            self.start_probability * self.starter_mean
            + (1.0 - self.start_probability) * self.bench_mean
        )

    @property
    def stddev(self) -> float:
        """Total standard deviation of the mixture, within-regime plus between-regime."""
        mean = self.expected_minutes
        within = (
            self.start_probability * self.starter_std**2
            + (1.0 - self.start_probability) * self.bench_std**2
        )
        between = (
            self.start_probability * (self.starter_mean - mean) ** 2
            + (1.0 - self.start_probability) * (self.bench_mean - mean) ** 2
        )
        return math.sqrt(max(0.0, within + between))

    def sample_regime(self, rng: random.Random) -> tuple[float, float]:
        """Draw a regime, returning its ``(centre, spread)``."""
        if rng.random() < self.start_probability:
            return self.starter_mean, self.starter_std
        return self.bench_mean, self.bench_std

    def shifted_to(self, expected_minutes: float) -> MinutesModel:
        """Translate both regimes so the mixture mean equals ``expected_minutes``.

        Used to honour the role model's headline projection -- which knows about injuries and
        teammate absences that raw history does not -- while keeping the bimodal shape that
        makes the tails honest. Shifting rather than rescaling, because the *gap* between
        starting and not starting is a property of the rotation, not of this particular night.

        Near the ends of the range a translation cannot get there: shifting a 31/12 rotation
        down to a mean of zero would clamp the bench regime at zero and leave the starter regime
        stranded above it, reporting nine minutes for a player projected to play none. When a
        pure translation would push either regime outside a basketball game, the model scales
        instead -- giving up the preserved gap to keep the mean it was asked for, because the
        mean is what the role model actually knows.
        """
        target = max(0.0, min(MAX_MINUTES, expected_minutes))
        current = self.expected_minutes
        offset = target - current
        starter = self.starter_mean + offset
        bench = self.bench_mean + offset

        if starter < 0.0 or bench < 0.0 or starter > MAX_MINUTES or bench > MAX_MINUTES:
            if current <= 0.0:
                starter = bench = target
            else:
                factor = target / current
                starter = self.starter_mean * factor
                bench = self.bench_mean * factor

        return MinutesModel(
            starter_mean=max(0.0, min(MAX_MINUTES, starter)),
            starter_std=self.starter_std,
            bench_mean=max(0.0, min(MAX_MINUTES, bench)),
            bench_std=self.bench_std,
            start_probability=self.start_probability,
        )


def _spread(values: Sequence[float], fallback: float) -> float:
    if len(values) < 2:
        return fallback
    mean = math.fsum(values) / len(values)
    variance = math.fsum((value - mean) ** 2 for value in values) / (len(values) - 1)
    return max(_MIN_MINUTES_STD, min(_MAX_MINUTES_STD, math.sqrt(variance)))


def build_minutes_model(
    minutes: Sequence[float],
    started: Sequence[bool],
    *,
    start_probability: float,
    half_life: float,
    expected_minutes: float | None = None,
    minutes_std: float | None = None,
) -> MinutesModel:
    """Fit starter and bench minutes regimes from history, oldest game first.

    When either regime is too thin to estimate, both collapse to the pooled distribution and
    the model degrades to the single Gaussian it replaced -- correct behaviour for a player who
    has started every game he has played.
    """
    if len(minutes) != len(started):
        raise ValueError("minutes and started must describe the same games")
    if not minutes:
        raise ValueError("cannot build a minutes model with no history")

    pooled_mean = weighted_mean(list(minutes), half_life)
    pooled_std = _spread(list(minutes), _MIN_MINUTES_STD)

    starter_games = [value for value, start in zip(minutes, started, strict=True) if start]
    bench_games = [value for value, start in zip(minutes, started, strict=True) if not start]
    probability = max(0.0, min(1.0, start_probability))

    if len(starter_games) >= _MIN_REGIME_GAMES and len(bench_games) >= _MIN_REGIME_GAMES:
        starter_mean = math.fsum(starter_games) / len(starter_games)
        bench_mean = math.fsum(bench_games) / len(bench_games)
        starter_std = _spread(starter_games, pooled_std)
        bench_std = _spread(bench_games, pooled_std)
    else:
        starter_mean = bench_mean = pooled_mean
        starter_std = bench_std = pooled_std
        # With one observed regime the start probability carries no information about minutes,
        # so it must not be allowed to shift the mixture mean away from the pooled estimate.
        probability = 1.0

    if minutes_std is not None:
        scale = max(_MIN_MINUTES_STD, min(_MAX_MINUTES_STD, minutes_std)) / max(
            _MIN_MINUTES_STD, pooled_std
        )
        starter_std = max(_MIN_MINUTES_STD, min(_MAX_MINUTES_STD, starter_std * scale))
        bench_std = max(_MIN_MINUTES_STD, min(_MAX_MINUTES_STD, bench_std * scale))

    model = MinutesModel(
        starter_mean=max(0.0, min(MAX_MINUTES, starter_mean)),
        starter_std=starter_std,
        bench_mean=max(0.0, min(MAX_MINUTES, bench_mean)),
        bench_std=bench_std,
        start_probability=probability,
    )
    if expected_minutes is not None:
        model = model.shifted_to(max(0.0, min(MAX_MINUTES, expected_minutes)))
    return model


@dataclass(frozen=True)
class JointSampler:
    """Paired per-game rates and standardised minutes deviations, plus recency weights."""

    rates: tuple[float, ...]
    minute_deviations: tuple[float, ...]
    weights: tuple[float, ...]

    def sample(
        self, rng: random.Random, model: MinutesModel, rate_multiplier: float
    ) -> tuple[float, float]:
        """Draw a coupled ``(minutes, rate)`` pair.

        The historical game supplies both its shrunk rate and the standardised amount by which
        its minutes departed from the player's norm. Re-centring that deviation on the sampled
        regime keeps the pairing intact while letting the role model move the whole
        distribution.
        """
        index = rng.choices(range(len(self.rates)), weights=list(self.weights), k=1)[0]
        centre, spread = model.sample_regime(rng)
        minutes = max(0.0, min(MAX_MINUTES, centre + self.minute_deviations[index] * spread))
        return minutes, max(0.0, self.rates[index] * rate_multiplier)


def build_joint_sampler(
    observations: Sequence[GameObservation], *, half_life: float
) -> JointSampler | None:
    """Shrink each game's rate by the minutes supporting it and pair it with that game's minutes.

    Returns ``None`` when no game has positive minutes, which is the caller's signal that this
    player has no usable rate history rather than a signal to invent one.
    """
    played = [observation for observation in observations if observation.minutes > 0.0]
    if not played:
        return None

    total_stat = math.fsum(observation.stat for observation in played)
    total_minutes = math.fsum(observation.minutes for observation in played)
    baseline_rate = total_stat / max(1e-9, total_minutes)

    minute_values = [observation.minutes for observation in played]
    mean_minutes = math.fsum(minute_values) / len(minute_values)
    spread = _spread(minute_values, _MIN_MINUTES_STD)

    rates: list[float] = []
    deviations: list[float] = []
    for observation in played:
        # Empirical-Bayes shrink toward the player's own overall rate. A long game barely
        # moves; a four-minute cameo is pulled most of the way back to the baseline.
        shrunk = (observation.stat + _RATE_PRIOR_MINUTES * baseline_rate) / (
            observation.minutes + _RATE_PRIOR_MINUTES
        )
        rates.append(max(0.0, shrunk))
        deviations.append((observation.minutes - mean_minutes) / spread)

    return JointSampler(
        rates=tuple(rates),
        minute_deviations=tuple(deviations),
        weights=half_life_weights(len(played), half_life),
    )
